new AC_Name[53][] =
{
	"AirBreak (onfoot)",
	"AirBreak (vehicle)",
	"Teleport (onfoot)",
	"Teleport (vehicle)",
	"Teleport (between vehicles)",
	"Teleport (vehicle to player)",
	"Teleport (Pickup)",
	"Fly Hack (on foot)",
	"Fly Hack (vehicle)",
	"Surf Fly",
	"Speed Hack",
	"Vehicle Repair",
	"Health Hack (player)",
	"Armor Hack (player)",
	"Money Hack",
	"Weapon Hack",
	"Ammo Hack (add)",
	"Ammo Hack (infinite)",
	"Special Actions Hack",
	"Bullet Godmode (onfoot)",
	"Bullet Godmode (vehicle)",
	"Invisible Hack",
	"Lagcomp Spoof",
	"Tuning Hack",
	"Parkour Mod",
	"Quick turn Mod",
	"Rapid Fire",
	"Fake Spawn",
	"Fake Kill",
	"Pro Aimbot",
	"CJ Run",
	"Car Shoot",
	"Instant Car Jack",
	"Unfreeze Mod",
	"AFK Ghost",
	"Full Aiming",
	"Fake NPC/Bot",
	"Auto/Fast Reconnect",
	"High Ping/Packetloss",
	"Dialog Spoofing",
	"Sandbox version",
	"Invalid version",
	"Rcon Bruteforce",
	"Tuning Crasher",
	"Invalid Seat Crasher",
	"Dialog Crasher",
	"Invalid toys",
	"Weapon Crasher",
	"Connection Flood",
	"Callback Flood",
	"Seat Flooding",
	"DDoS",
	"Fake NOPs"
};
